USE cinefy;

INSERT INTO genres (name) VALUES
('Action'),
('Adventure'),
('Animation'),
('Biography'),
('Comedy'),
('Crime'),
('Drama'),
('Fantasy'),
('Horror'),
('Mystery'),
('Romance'),
('Sci-Fi'),
('Thriller'),
('War'),
('Western')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO movies (genreId, title, slug, description, releaseYear, duration, poster, director) VALUES
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Interstellar', 'interstellar', 'A team travels through a wormhole in search of a new home for humanity.', 2014, 169, 'posters/interstellar.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Oppenheimer', 'oppenheimer', 'The story of J. Robert Oppenheimer and the creation of the atomic bomb during World War II.', 2023, 180, 'posters/oppenheimer.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'Romance'), 'La La Land', 'la-la-land', 'A jazz pianist and an aspiring actor fall in love while chasing their dreams in Los Angeles.', 2016, 128, 'posters/la-la-land.webp', 'Damien Chazelle'),
((SELECT id FROM genres WHERE name = 'Romance'), 'About Time', 'about-time', 'A young man uses his ability to travel through time to improve love, family, and ordinary days.', 2013, 123, 'posters/about-time.webp', 'Richard Curtis'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'In Time', 'in-time', 'In a future where time is currency, one man challenges a system built to keep the poor running.', 2011, 109, 'posters/in-time.webp', 'Andrew Niccol'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Back to the Future', 'back-to-the-future', 'A teenager is sent to 1955 in a time machine and must make sure his parents fall in love.', 1985, 116, 'posters/back-to-the-future.webp', 'Robert Zemeckis'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Back to the Future Part II', 'back-to-the-future-part-ii', 'Marty and Doc leap between futures and alternate timelines to repair a dangerous mistake.', 1989, 108, 'posters/back-to-the-future-part-ii.webp', 'Robert Zemeckis'),
((SELECT id FROM genres WHERE name = 'Western'), 'Back to the Future Part III', 'back-to-the-future-part-iii', 'Marty travels to the Old West to rescue Doc and find a way back to his own time.', 1990, 118, 'posters/back-to-the-future-part-iii.webp', 'Robert Zemeckis'),
((SELECT id FROM genres WHERE name = 'Crime'), 'The Godfather', 'the-godfather', 'The aging patriarch of a crime family transfers power to a reluctant son.', 1972, 175, 'posters/the-godfather.webp', 'Francis Ford Coppola'),
((SELECT id FROM genres WHERE name = 'Crime'), 'The Godfather Part II', 'the-godfather-part-ii', 'Michael Corleone expands his empire as the early life of his father is revealed.', 1974, 202, 'posters/the-godfather-part-ii.webp', 'Francis Ford Coppola'),
((SELECT id FROM genres WHERE name = 'Crime'), 'The Godfather Part III', 'the-godfather-part-iii', 'An aging Michael Corleone seeks legitimacy while old sins pull his family back into danger.', 1990, 162, 'posters/the-godfather-part-iii.webp', 'Francis Ford Coppola'),
((SELECT id FROM genres WHERE name = 'Drama'), 'The Shawshank Redemption', 'the-shawshank-redemption', 'Two imprisoned men build a friendship around hope, patience, and quiet resistance.', 1994, 142, 'posters/the-shawshank-redemption.webp', 'Frank Darabont'),
((SELECT id FROM genres WHERE name = 'Crime'), 'The Dark Knight', 'the-dark-knight', 'Batman faces the Joker, a criminal force determined to push Gotham into chaos.', 2008, 152, 'posters/the-dark-knight.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'Drama'), '12 Angry Men', '12-angry-men', 'A lone juror questions a murder verdict and forces the room to examine its certainty.', 1957, 96, 'posters/12-angry-men.webp', 'Sidney Lumet'),
((SELECT id FROM genres WHERE name = 'Crime'), 'Pulp Fiction', 'pulp-fiction', 'Interlocking Los Angeles crime stories unfold with dark humor and sudden violence.', 1994, 154, 'posters/pulp-fiction.webp', 'Quentin Tarantino'),
((SELECT id FROM genres WHERE name = 'Fantasy'), 'The Lord of the Rings: The Fellowship of the Ring', 'the-lord-of-the-rings-the-fellowship-of-the-ring', 'A young hobbit begins a perilous journey to destroy a powerful ring.', 2001, 178, 'posters/the-lord-of-the-rings-the-fellowship-of-the-ring.webp', 'Peter Jackson'),
((SELECT id FROM genres WHERE name = 'Fantasy'), 'The Lord of the Rings: The Two Towers', 'the-lord-of-the-rings-the-two-towers', 'The fellowship is scattered as war grows across Middle-earth.', 2002, 179, 'posters/the-lord-of-the-rings-the-two-towers.webp', 'Peter Jackson'),
((SELECT id FROM genres WHERE name = 'Fantasy'), 'The Lord of the Rings: The Return of the King', 'the-lord-of-the-rings-the-return-of-the-king', 'Final battles decide the fate of Middle-earth while Frodo reaches Mordor.', 2003, 201, 'posters/the-lord-of-the-rings-the-return-of-the-king.webp', 'Peter Jackson'),
((SELECT id FROM genres WHERE name = 'Western'), 'The Good, the Bad and the Ugly', 'the-good-the-bad-and-the-ugly', 'Three gunslingers race across the Civil War frontier in search of buried gold.', 1966, 178, 'posters/the-good-the-bad-and-the-ugly.webp', 'Sergio Leone'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Forrest Gump', 'forrest-gump', 'A kindhearted man drifts through decades of American history while holding onto love.', 1994, 142, 'posters/forrest-gump.webp', 'Robert Zemeckis'),
((SELECT id FROM genres WHERE name = 'Crime'), 'Goodfellas', 'goodfellas', 'A young man rises through the mob and discovers the cost of life inside organized crime.', 1990, 145, 'posters/goodfellas.webp', 'Martin Scorsese'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'The Matrix', 'the-matrix', 'A hacker discovers reality is a simulation and joins a rebellion against machine control.', 1999, 136, 'posters/the-matrix.webp', 'Lana Wachowski'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Fight Club', 'fight-club', 'An alienated office worker forms an underground club that grows beyond his control.', 1999, 139, 'posters/fight-club.webp', 'David Fincher'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Inception', 'inception', 'A thief who steals secrets through dreams attempts one final impossible job.', 2010, 148, 'posters/inception.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Whiplash', 'whiplash', 'A young drummer endures brutal training under a fearsome music instructor.', 2014, 107, 'posters/whiplash.webp', 'Damien Chazelle'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Se7en', 'se7en', 'Two detectives hunt a serial killer staging murders around the seven deadly sins.', 1995, 127, 'posters/se7en.webp', 'David Fincher'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'The Silence of the Lambs', 'the-silence-of-the-lambs', 'An FBI trainee seeks help from a brilliant imprisoned killer to catch another murderer.', 1991, 118, 'posters/the-silence-of-the-lambs.webp', 'Jonathan Demme'),
((SELECT id FROM genres WHERE name = 'Biography'), 'Schindler''s List', 'schindlers-list', 'A German industrialist saves Jewish workers during the Holocaust.', 1993, 195, 'posters/schindlers-list.webp', 'Steven Spielberg'),
((SELECT id FROM genres WHERE name = 'War'), 'Saving Private Ryan', 'saving-private-ryan', 'A squad of soldiers searches for one missing paratrooper after the Normandy invasion.', 1998, 169, 'posters/saving-private-ryan.webp', 'Steven Spielberg'),
((SELECT id FROM genres WHERE name = 'Drama'), 'The Green Mile', 'the-green-mile', 'A death row guard encounters a gentle prisoner with a mysterious gift.', 1999, 189, 'posters/the-green-mile.webp', 'Frank Darabont'),
((SELECT id FROM genres WHERE name = 'Drama'), 'The Prestige', 'the-prestige', 'Two rival magicians sacrifice everything in pursuit of the perfect illusion.', 2006, 130, 'posters/the-prestige.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'Crime'), 'The Departed', 'the-departed', 'An undercover cop and a criminal mole try to uncover each other in Boston.', 2006, 151, 'posters/the-departed.webp', 'Martin Scorsese'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Gladiator', 'gladiator', 'A betrayed Roman general becomes a gladiator and seeks justice against an emperor.', 2000, 155, 'posters/gladiator.webp', 'Ridley Scott'),
((SELECT id FROM genres WHERE name = 'Drama'), 'The Lion King', 'the-lion-king', 'A young lion prince must reclaim his kingdom after tragedy and exile.', 1994, 88, 'posters/the-lion-king.webp', 'Roger Allers'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Terminator 2: Judgment Day', 'terminator-2-judgment-day', 'A reprogrammed cyborg protects a boy from a more advanced assassin.', 1991, 137, 'posters/terminator-2-judgment-day.webp', 'James Cameron'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Alien', 'alien', 'A commercial spaceship crew is hunted by a deadly organism after a distress call.', 1979, 117, 'posters/alien.webp', 'Ridley Scott'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Aliens', 'aliens', 'Ripley returns with marines to face a colony overrun by alien creatures.', 1986, 137, 'posters/aliens.webp', 'James Cameron'),
((SELECT id FROM genres WHERE name = 'Action'), 'Die Hard', 'die-hard', 'A New York cop battles terrorists inside a Los Angeles skyscraper.', 1988, 132, 'posters/die-hard.webp', 'John McTiernan'),
((SELECT id FROM genres WHERE name = 'Adventure'), 'Raiders of the Lost Ark', 'raiders-of-the-lost-ark', 'Indiana Jones races rivals to find the biblical Ark of the Covenant.', 1981, 115, 'posters/raiders-of-the-lost-ark.webp', 'Steven Spielberg'),
((SELECT id FROM genres WHERE name = 'Adventure'), 'Indiana Jones and the Last Crusade', 'indiana-jones-and-the-last-crusade', 'Indiana Jones searches for his father and the legendary Holy Grail.', 1989, 127, 'posters/indiana-jones-and-the-last-crusade.webp', 'Steven Spielberg'),
((SELECT id FROM genres WHERE name = 'Adventure'), 'Jurassic Park', 'jurassic-park', 'A theme park of cloned dinosaurs turns deadly when its systems fail.', 1993, 127, 'posters/jurassic-park.webp', 'Steven Spielberg'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Blade Runner', 'blade-runner', 'A weary detective hunts synthetic humans in a neon future Los Angeles.', 1982, 117, 'posters/blade-runner.webp', 'Ridley Scott'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Blade Runner 2049', 'blade-runner-2049', 'A replicant officer uncovers a secret that could reshape the future.', 2017, 164, 'posters/blade-runner-2049.webp', 'Denis Villeneuve'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'Prisoners', 'prisoners', 'A desperate father and a determined detective search for two missing girls.', 2013, 153, 'posters/prisoners.webp', 'Denis Villeneuve'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Arrival', 'arrival', 'A linguist works to communicate with alien visitors before global fear erupts.', 2016, 116, 'posters/arrival.webp', 'Denis Villeneuve'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Dune', 'dune-2021', 'A noble family enters a desert world where politics, prophecy, and survival collide.', 2021, 155, 'posters/dune.webp', 'Denis Villeneuve'),
((SELECT id FROM genres WHERE name = 'Sci-Fi'), 'Dune: Part Two', 'dune-part-two', 'Paul Atreides joins the Fremen and confronts the path of revenge and prophecy.', 2024, 166, 'posters/dune-part-two.webp', 'Denis Villeneuve'),
((SELECT id FROM genres WHERE name = 'Action'), 'Mad Max: Fury Road', 'mad-max-fury-road', 'A rebel driver and a drifter flee across the wasteland with a warlord in pursuit.', 2015, 120, 'posters/mad-max-fury-road.webp', 'George Miller'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Spider-Man: Into the Spider-Verse', 'spider-man-into-the-spider-verse', 'Miles Morales discovers a multiverse of Spider-heroes and learns to become his own.', 2018, 117, 'posters/spider-man-into-the-spider-verse.webp', 'Bob Persichetti'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Spider-Man: Across the Spider-Verse', 'spider-man-across-the-spider-verse', 'Miles Morales journeys through the multiverse and challenges the rules of heroism.', 2023, 140, 'posters/spider-man-across-the-spider-verse.webp', 'Joaquim Dos Santos'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Toy Story', 'toy-story', 'A cowboy doll feels threatened when a flashy space toy joins the room.', 1995, 81, 'posters/toy-story.webp', 'John Lasseter'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Toy Story 2', 'toy-story-2', 'Woody is stolen by a collector and must choose between fame and friendship.', 1999, 92, 'posters/toy-story-2.webp', 'John Lasseter'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Toy Story 3', 'toy-story-3', 'Andy''s toys face an uncertain future as their owner prepares for college.', 2010, 103, 'posters/toy-story-3.webp', 'Lee Unkrich'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Finding Nemo', 'finding-nemo', 'A timid clownfish crosses the ocean to rescue his captured son.', 2003, 100, 'posters/finding-nemo.webp', 'Andrew Stanton'),
((SELECT id FROM genres WHERE name = 'Animation'), 'WALL-E', 'wall-e', 'A lonely trash-compacting robot discovers love and hope on an abandoned Earth.', 2008, 98, 'posters/wall-e.webp', 'Andrew Stanton'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Up', 'up', 'A widower lifts his house with balloons and accidentally brings a young scout along.', 2009, 96, 'posters/up.webp', 'Pete Docter'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Inside Out', 'inside-out', 'The emotions inside a young girl navigate a life-changing move.', 2015, 95, 'posters/inside-out.webp', 'Pete Docter'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Coco', 'coco', 'A boy enters the Land of the Dead to uncover his family history and love of music.', 2017, 105, 'posters/coco.webp', 'Lee Unkrich'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Spirited Away', 'spirited-away', 'A girl enters a spirit world and must find courage to save her parents.', 2001, 125, 'posters/spirited-away.webp', 'Hayao Miyazaki'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Princess Mononoke', 'princess-mononoke', 'A cursed prince is drawn into a war between forest gods and industrial humans.', 1997, 134, 'posters/princess-mononoke.webp', 'Hayao Miyazaki'),
((SELECT id FROM genres WHERE name = 'Animation'), 'Howl''s Moving Castle', 'howls-moving-castle', 'A young woman cursed with old age finds refuge in a wizard''s walking castle.', 2004, 119, 'posters/howls-moving-castle.webp', 'Hayao Miyazaki'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Parasite', 'parasite', 'A poor family infiltrates a wealthy household, triggering a sharp class thriller.', 2019, 132, 'posters/parasite.webp', 'Bong Joon Ho'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Memories of Murder', 'memories-of-murder', 'Detectives struggle to solve a series of killings in rural South Korea.', 2003, 132, 'posters/memories-of-murder.webp', 'Bong Joon Ho'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Oldboy', 'oldboy', 'A man imprisoned for years searches for the truth behind his captivity.', 2003, 120, 'posters/oldboy.webp', 'Park Chan-wook'),
((SELECT id FROM genres WHERE name = 'Drama'), 'City of God', 'city-of-god', 'Young people grow up amid violence and ambition in Rio de Janeiro.', 2002, 130, 'posters/city-of-god.webp', 'Fernando Meirelles'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Amelie', 'amelie', 'A shy Parisian waitress quietly changes lives while searching for her own happiness.', 2001, 122, 'posters/amelie.webp', 'Jean-Pierre Jeunet'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Life Is Beautiful', 'life-is-beautiful', 'A father uses imagination to shield his son from the horrors of a concentration camp.', 1997, 116, 'posters/life-is-beautiful.webp', 'Roberto Benigni'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Cinema Paradiso', 'cinema-paradiso', 'A filmmaker remembers the projectionist who nurtured his childhood love of movies.', 1988, 124, 'posters/cinema-paradiso.webp', 'Giuseppe Tornatore'),
((SELECT id FROM genres WHERE name = 'Drama'), 'The Intouchables', 'the-intouchables', 'An unlikely friendship forms between a wealthy quadriplegic and his caregiver.', 2011, 112, 'posters/the-intouchables.webp', 'Olivier Nakache'),
((SELECT id FROM genres WHERE name = 'Action'), 'Seven Samurai', 'seven-samurai', 'Villagers hire masterless samurai to defend their home from bandits.', 1954, 207, 'posters/seven-samurai.webp', 'Akira Kurosawa'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Rashomon', 'rashomon', 'Conflicting accounts of a crime reveal the instability of truth and memory.', 1950, 88, 'posters/rashomon.webp', 'Akira Kurosawa'),
((SELECT id FROM genres WHERE name = 'Drama'), 'Ikiru', 'ikiru', 'A bureaucrat with terminal cancer searches for meaning in his remaining days.', 1952, 143, 'posters/ikiru.webp', 'Akira Kurosawa'),
((SELECT id FROM genres WHERE name = 'Western'), 'Unforgiven', 'unforgiven', 'An aging outlaw takes one last job and confronts the myths of violence.', 1992, 130, 'posters/unforgiven.webp', 'Clint Eastwood'),
((SELECT id FROM genres WHERE name = 'Western'), 'Django Unchained', 'django-unchained', 'A freed man joins a bounty hunter to rescue his wife from slavery.', 2012, 165, 'posters/django-unchained.webp', 'Quentin Tarantino'),
((SELECT id FROM genres WHERE name = 'Western'), 'No Country for Old Men', 'no-country-for-old-men', 'A hunter finds drug money and is pursued by a relentless killer.', 2007, 122, 'posters/no-country-for-old-men.webp', 'Joel Coen'),
((SELECT id FROM genres WHERE name = 'Drama'), 'There Will Be Blood', 'there-will-be-blood', 'An oil prospector builds an empire while his hunger for power consumes him.', 2007, 158, 'posters/there-will-be-blood.webp', 'Paul Thomas Anderson'),
((SELECT id FROM genres WHERE name = 'Drama'), 'The Social Network', 'the-social-network', 'The rise of Facebook becomes a story of ambition, lawsuits, and betrayal.', 2010, 120, 'posters/the-social-network.webp', 'David Fincher'),
((SELECT id FROM genres WHERE name = 'Biography'), 'The Imitation Game', 'the-imitation-game', 'Alan Turing and his team race to break the Enigma code during World War II.', 2014, 114, 'posters/the-imitation-game.webp', 'Morten Tyldum'),
((SELECT id FROM genres WHERE name = 'Biography'), 'The Theory of Everything', 'the-theory-of-everything', 'Stephen Hawking faces illness while building a life and reshaping physics.', 2014, 123, 'posters/the-theory-of-everything.webp', 'James Marsh'),
((SELECT id FROM genres WHERE name = 'Biography'), 'A Beautiful Mind', 'a-beautiful-mind', 'Mathematician John Nash struggles with genius, love, and mental illness.', 2001, 135, 'posters/a-beautiful-mind.webp', 'Ron Howard'),
((SELECT id FROM genres WHERE name = 'Biography'), 'The Pianist', 'the-pianist', 'A Polish Jewish musician survives the destruction of Warsaw during World War II.', 2002, 150, 'posters/the-pianist.webp', 'Roman Polanski'),
((SELECT id FROM genres WHERE name = 'War'), '1917', '1917', 'Two soldiers cross enemy territory to deliver a message that could save hundreds.', 2019, 119, 'posters/1917.webp', 'Sam Mendes'),
((SELECT id FROM genres WHERE name = 'War'), 'Dunkirk', 'dunkirk', 'Allied soldiers are evacuated from a surrounded beach during World War II.', 2017, 106, 'posters/dunkirk.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'War'), 'Apocalypse Now', 'apocalypse-now', 'A captain journeys upriver through the Vietnam War to confront a rogue colonel.', 1979, 147, 'posters/apocalypse-now.webp', 'Francis Ford Coppola'),
((SELECT id FROM genres WHERE name = 'War'), 'Full Metal Jacket', 'full-metal-jacket', 'Marine recruits endure brutal training before the violence of Vietnam.', 1987, 116, 'posters/full-metal-jacket.webp', 'Stanley Kubrick'),
((SELECT id FROM genres WHERE name = 'War'), 'Hacksaw Ridge', 'hacksaw-ridge', 'A pacifist medic saves lives on Okinawa without carrying a weapon.', 2016, 139, 'posters/hacksaw-ridge.webp', 'Mel Gibson'),
((SELECT id FROM genres WHERE name = 'Action'), 'The Raid: Redemption', 'the-raid-redemption', 'A police squad fights floor by floor through a tower controlled by criminals.', 2011, 101, 'posters/the-raid-redemption.webp', 'Gareth Evans'),
((SELECT id FROM genres WHERE name = 'Action'), 'John Wick', 'john-wick', 'A retired assassin returns to the underworld after a personal loss.', 2014, 101, 'posters/john-wick.webp', 'Chad Stahelski'),
((SELECT id FROM genres WHERE name = 'Action'), 'John Wick: Chapter 2', 'john-wick-chapter-2', 'John Wick is pulled back into a blood oath and hunted by assassins.', 2017, 122, 'posters/john-wick-chapter-2.webp', 'Chad Stahelski'),
((SELECT id FROM genres WHERE name = 'Action'), 'John Wick: Chapter 3 - Parabellum', 'john-wick-chapter-3-parabellum', 'John Wick fights for survival after a global bounty is placed on him.', 2019, 130, 'posters/john-wick-chapter-3-parabellum.webp', 'Chad Stahelski'),
((SELECT id FROM genres WHERE name = 'Action'), 'John Wick: Chapter 4', 'john-wick-chapter-4', 'John Wick challenges the High Table in a final path toward freedom.', 2023, 169, 'posters/john-wick-chapter-4.webp', 'Chad Stahelski'),
((SELECT id FROM genres WHERE name = 'Action'), 'Mission: Impossible - Fallout', 'mission-impossible-fallout', 'Ethan Hunt races to stop a nuclear threat after a mission goes wrong.', 2018, 147, 'posters/mission-impossible-fallout.webp', 'Christopher McQuarrie'),
((SELECT id FROM genres WHERE name = 'Action'), 'Top Gun: Maverick', 'top-gun-maverick', 'A veteran pilot trains elite graduates for a dangerous mission.', 2022, 130, 'posters/top-gun-maverick.webp', 'Joseph Kosinski'),
((SELECT id FROM genres WHERE name = 'Action'), 'Heat', 'heat', 'A master thief and a relentless detective circle each other in Los Angeles.', 1995, 170, 'posters/heat.webp', 'Michael Mann'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Collateral', 'collateral', 'A cab driver is forced to chauffeur a hitman through one night in Los Angeles.', 2004, 120, 'posters/collateral.webp', 'Michael Mann'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Nightcrawler', 'nightcrawler', 'An ambitious freelancer films violent crime scenes for local television news.', 2014, 117, 'posters/nightcrawler.webp', 'Dan Gilroy'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Gone Girl', 'gone-girl', 'A missing woman case turns into a media storm around a troubled marriage.', 2014, 149, 'posters/gone-girl.webp', 'David Fincher'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'Zodiac', 'zodiac', 'Journalists and detectives obsess over the unsolved Zodiac killings.', 2007, 157, 'posters/zodiac.webp', 'David Fincher'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'Shutter Island', 'shutter-island', 'A marshal investigates a disappearance at a remote psychiatric hospital.', 2010, 138, 'posters/shutter-island.webp', 'Martin Scorsese'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'Memento', 'memento', 'A man with short-term memory loss hunts for his wife''s killer using notes and tattoos.', 2000, 113, 'posters/memento.webp', 'Christopher Nolan'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'Knives Out', 'knives-out', 'A detective investigates a wealthy author''s death and a family full of motives.', 2019, 130, 'posters/knives-out.webp', 'Rian Johnson'),
((SELECT id FROM genres WHERE name = 'Mystery'), 'Glass Onion', 'glass-onion', 'Detective Benoit Blanc joins a tech billionaire''s island gathering where murder awaits.', 2022, 139, 'posters/glass-onion.webp', 'Rian Johnson'),
((SELECT id FROM genres WHERE name = 'Horror'), 'Get Out', 'get-out', 'A young man visits his girlfriend''s family and uncovers a terrifying secret.', 2017, 104, 'posters/get-out.webp', 'Jordan Peele'),
((SELECT id FROM genres WHERE name = 'Horror'), 'Us', 'us', 'A family vacation becomes a nightmare when their doubles appear.', 2019, 116, 'posters/us.webp', 'Jordan Peele'),
((SELECT id FROM genres WHERE name = 'Horror'), 'Nope', 'nope', 'Siblings running a horse ranch investigate a strange presence in the sky.', 2022, 130, 'posters/nope.webp', 'Jordan Peele'),
((SELECT id FROM genres WHERE name = 'Horror'), 'Hereditary', 'hereditary', 'A grieving family is pulled into a terrifying legacy after a death.', 2018, 127, 'posters/hereditary.webp', 'Ari Aster'),
((SELECT id FROM genres WHERE name = 'Horror'), 'Midsommar', 'midsommar', 'A group of friends visits a remote festival where beauty hides ritual horror.', 2019, 148, 'posters/midsommar.webp', 'Ari Aster'),
((SELECT id FROM genres WHERE name = 'Horror'), 'The Shining', 'the-shining', 'A caretaker and his family are isolated in a hotel with a violent past.', 1980, 146, 'posters/the-shining.webp', 'Stanley Kubrick'),
((SELECT id FROM genres WHERE name = 'Horror'), 'Psycho', 'psycho', 'A secretary on the run stops at a lonely motel with a disturbing owner.', 1960, 109, 'posters/psycho.webp', 'Alfred Hitchcock'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Rear Window', 'rear-window', 'A photographer confined to his apartment suspects a neighbor of murder.', 1954, 112, 'posters/rear-window.webp', 'Alfred Hitchcock'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'Vertigo', 'vertigo', 'A former detective becomes obsessed with a woman he is hired to follow.', 1958, 128, 'posters/vertigo.webp', 'Alfred Hitchcock'),
((SELECT id FROM genres WHERE name = 'Thriller'), 'North by Northwest', 'north-by-northwest', 'An advertising executive is mistaken for a spy and chased across the country.', 1959, 136, 'posters/north-by-northwest.webp', 'Alfred Hitchcock'),
((SELECT id FROM genres WHERE name = 'Romance'), 'Eternal Sunshine of the Spotless Mind', 'eternal-sunshine-of-the-spotless-mind', 'Former lovers erase each other from memory and rediscover what they shared.', 2004, 108, 'posters/eternal-sunshine-of-the-spotless-mind.webp', 'Michel Gondry'),
((SELECT id FROM genres WHERE name = 'Romance'), 'Before Sunrise', 'before-sunrise', 'Two strangers spend one night walking and talking through Vienna.', 1995, 101, 'posters/before-sunrise.webp', 'Richard Linklater'),
((SELECT id FROM genres WHERE name = 'Romance'), 'Before Sunset', 'before-sunset', 'Two former strangers reconnect in Paris years after a brief encounter.', 2004, 80, 'posters/before-sunset.webp', 'Richard Linklater'),
((SELECT id FROM genres WHERE name = 'Romance'), 'Before Midnight', 'before-midnight', 'A couple confronts the tensions of love and time during a Greek holiday.', 2013, 109, 'posters/before-midnight.webp', 'Richard Linklater'),
((SELECT id FROM genres WHERE name = 'Romance'), 'The Notebook', 'the-notebook', 'A lifelong romance is remembered through a story read in a nursing home.', 2004, 123, 'posters/the-notebook.webp', 'Nick Cassavetes'),
((SELECT id FROM genres WHERE name = 'Romance'), 'Pride & Prejudice', 'pride-and-prejudice-2005', 'Elizabeth Bennet and Mr. Darcy clash, misunderstand, and slowly fall in love.', 2005, 129, 'posters/pride-and-prejudice-2005.webp', 'Joe Wright'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'The Grand Budapest Hotel', 'the-grand-budapest-hotel', 'A concierge and lobby boy become entangled in theft, romance, and political danger.', 2014, 99, 'posters/the-grand-budapest-hotel.webp', 'Wes Anderson'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'Jojo Rabbit', 'jojo-rabbit', 'A lonely boy in Nazi Germany discovers his mother is hiding a Jewish girl.', 2019, 108, 'posters/jojo-rabbit.webp', 'Taika Waititi'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'The Truman Show', 'the-truman-show', 'A man slowly realizes his entire life is a carefully staged television program.', 1998, 103, 'posters/the-truman-show.webp', 'Peter Weir'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'Groundhog Day', 'groundhog-day', 'A cynical weatherman relives the same day until he learns how to change.', 1993, 101, 'posters/groundhog-day.webp', 'Harold Ramis'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'Little Miss Sunshine', 'little-miss-sunshine', 'A dysfunctional family takes a road trip to a children''s beauty pageant.', 2006, 101, 'posters/little-miss-sunshine.webp', 'Jonathan Dayton'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'The Big Lebowski', 'the-big-lebowski', 'A laid-back bowler is pulled into a kidnapping plot after a case of mistaken identity.', 1998, 117, 'posters/the-big-lebowski.webp', 'Joel Coen'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'Superbad', 'superbad', 'Two high school friends try to make one memorable night before graduation.', 2007, 113, 'posters/superbad.webp', 'Greg Mottola'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'Bridesmaids', 'bridesmaids', 'A struggling baker spirals while serving as maid of honor for her best friend.', 2011, 125, 'posters/bridesmaids.webp', 'Paul Feig'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'Mean Girls', 'mean-girls', 'A new student enters a high school social hierarchy ruled by a popular clique.', 2004, 97, 'posters/mean-girls.webp', 'Mark Waters'),
((SELECT id FROM genres WHERE name = 'Comedy'), 'The Princess Bride', 'the-princess-bride', 'A farmhand, a princess, and a band of odd heroes cross paths in a fairy-tale adventure.', 1987, 98, 'posters/the-princess-bride.webp', 'Rob Reiner')
ON DUPLICATE KEY UPDATE
    genreId = VALUES(genreId),
    title = VALUES(title),
    description = VALUES(description),
    releaseYear = VALUES(releaseYear),
    duration = VALUES(duration),
    poster = VALUES(poster),
    director = VALUES(director);
